// Source: 1000 Genomes Project, Affymetrix 6.0 genotype chip, sample NA12878.
// Real, public, open-consent data — nothing here is synthetic.
//   https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/hd_genotype_chip/
// The full extract is ~888k markers / 22 MB, which is the right thing to drag
// onto the page from disk but too heavy to ship inside a JS chunk. This keeps
// every marker that ClinVar annotates (so the analysis tools have real hits)
// plus an evenly spaced subsample of the rest, preserving genome-wide coverage
// and the original chromosome/position ordering.
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "data-build/NA12878.chip.txt";
const OUT = "src/data/demo.data.js";
const TARGET_MARKERS = 250_000;

const { CLINVAR_TSV } = await import("../src/data/clinvar.data.js");
const annotated = new Set(
  CLINVAR_TSV.split("\n").map((rec) => Number(rec.slice(0, rec.indexOf("\t"))))
);
console.log(`ClinVar rs ids available: ${annotated.size}`);

const lines = readFileSync(SRC, "utf8").split("\n");
const rows = lines.filter(
  (l) => l && !l.startsWith("#") && !l.startsWith("rsid")
);

const rsOf = (l) => Number(l.slice(2, l.indexOf("\t")));
const keepAlways = rows.filter((l) => annotated.has(rsOf(l)));
const rest = rows.filter((l) => !annotated.has(rsOf(l)));

// Spread the sample across the whole array. Taking every Nth row and then
// truncating to `need` would silently drop the tail of the genome — the first
// version of this script did exactly that and lost chromosomes 18 through MT.
const need = Math.min(
  rest.length,
  Math.max(0, TARGET_MARKERS - keepAlways.length)
);
const sampled = [];
for (let k = 0; k < need; k++) {
  sampled.push(rest[Math.floor((k * rest.length) / need)]);
}

const kept = new Set([...keepAlways, ...sampled]);
const out = rows.filter((l) => kept.has(l));

const chroms = new Set(out.map((l) => l.split("\t")[1]));
const body = [
  "# Demo dataset for LocusLocal.",
  "# Source: 1000 Genomes Project, Affymetrix 6.0 genotype chip, sample NA12878.",
  "# Real, public, open-consent human genotypes from a consenting donor.",
  "# This is measured data, not simulated, and it is not your own genome.",
  `# Subset: ${out.length} of ${rows.length} markers, keeping every ClinVar-annotated`,
  "# marker plus an evenly spaced sample of the rest. Reference build: GRCh37/hg19.",
  "rsid\tchromosome\tposition\tgenotype",
  ...out,
].join("\n");

writeFileSync(
  OUT,
  `// GENERATED by scripts/build-demo.mjs - do not edit.
export const DEMO_FILENAME = "NA12878.1000genomes.affy6.demo.txt"
export const DEMO_MARKERS = ${out.length}
export const DEMO_PROVENANCE = ${JSON.stringify(
    "1000 Genomes Project, Affymetrix 6.0 genotype chip, sample NA12878 — real, public, open-consent data"
  )}
export const DEMO_TSV = ${JSON.stringify(body)}
`
);

console.log(`source markers   ${rows.length}`);
console.log(`ClinVar-annotated kept in full: ${keepAlways.length}`);
console.log(`subsampled evenly:              ${sampled.length}`);
console.log(`total markers    ${out.length} across ${chroms.size} chromosomes`);
console.log(`raw TSV ${(body.length / 1e6).toFixed(2)} MB -> ${OUT}`);
